# Inventory for the rpi k3s homelab.
# Edit hostnames / IPs to match your DHCP reservations.

[k3s_server]
# rpi-control  ansible_host=rpi-control.local
rpi-control  ansible_host=192.168.4.92

[k3s_agent]
# rpi-node1    ansible_host=rpi-node1.local
rpi-node1    ansible_host=192.168.4.95
# rpi-node2    ansible_host=rpi-node2.local
rpi-node2    ansible_host=192.168.4.91
# rpi-node3    ansible_host=rpi-node3.local
rpi-node3    ansible_host=192.168.4.94
# rpi-node4  ansible_host=rpi-node4.local
# rpi-node4  ansible_host=

[k3s_cluster:children]
k3s_server
k3s_agent

[k3s_cluster:vars]
ansible_user=victord
ansible_python_interpreter=/usr/bin/python3
